### ISSUE TITLE
Apple Silicon native version

### ISSUE THREAD

**Issue by lopcode** [elgatosf/streamdeck-obs-plugin2#1]
Hi there,

I submitted an issue on the previous version of the plugin, but the repository is now archived, so I'm making another here for the same issue: https://github.com/elgatosf/streamdeck-obs-plugin/issues/15

The build instructions are much improved (thanks!) but building on an Apple Silicon device (ARM 64) is not supported:

```
CMake Warning at CMakeLists.txt:94 (message):
  StreamDeck: Failed to detect version, using default instead.


-- StreamDeck: Version 5.0.5.0-00000000
-- Targetting ARM with 64bits and a pointer size of 64bit.
-- Applying custom flags for GNU style build.
-- StreamDeck: This is a standalone build.
CMake Error at CMakeLists.txt:400 (message):
  StreamDeck: Platform 'macos' with architecture 'ARM' and bitness '64' is
  not supported.
```

Mainline OBS now supports native ARM64/Apple Silicon, and the existing Stream Deck plugin doesn't yet function when using this native version of OBS.

**Comment by lopcode** [comment]
I had a chance to look at this myself, and decided using the obs-plugintemplate was the best way to go.

This is a very quick attempt, and I'm not great with CMake, but copying source in and following the setup instructions from the parent repo was good enough to get something to build https://github.com/CarrotCodes/streamdeck-obs

After running the compiled installer, it seems there are no source changes otherwise needed to get the Stream Deck running on an Apple Silicon build of OBS 🎉 

Edit: took the time to refactor it (pulling this repo in as a submodule) and get the GitHub Actions workflows running - there are prebuilt binaries available on the 1.0.0 release: https://github.com/CarrotCodes/streamdeck-obs/releases/tag/1.0.0

Shown: the Stream Deck app picking up scenes from my native build of OBS
<img width="846" alt="Screenshot 2022-07-25 at 01 13 42" src="https://user-images.githubusercontent.com/149851/180671844-a430fa7c-16b4-411d-afe1-bfa24a43d93f.png">

**Comment by kilinbox** [comment]
It seems that to support the Apple Silicon native version, it is necessary to add libraries for the arm64 architecture.

example.
https://github.com/kilinbox/streamdeck-obs-plugin2/tree/arm64

However, this is not enough since the framework will be Qt6 in OBS 28.0. the Qt library needs to be changed from Qt5 to Qt6.
may need to change some of the code as well as CMakeLists.txt.

**Comment by lopcode** [comment]
Yesterday I took some time to make Qt 6 builds, if anyone's interested in the obs-plugintemplate changes needed: https://github.com/CarrotCodes/streamdeck-obs/commit/7451fe39e5457efef44d3f0f37d11935571f5cb2

Builds (only works with OBS master builds made after yesterday): https://github.com/CarrotCodes/streamdeck-obs/releases

One point of weirdness that needed source changes was the plugin's use of `obs_queue_task` - with `wait` set to false, the callbacks never fire. I'm not sure if that's undefined behaviour because of something else the plugin is doing or not, but for now, setting `wait` to true and blocking until the async tasks get completed works fine.

**Comment by kilinbox** [comment]
@CarrotCodes 
Great! The plugin you built worked in my environment too. Thank you very much.

**Comment by Nyarumi** [comment]
@CarrotCodes thank you for your work. I can confirm that the plugin works with OBS 28 RC2 for me on macOS Monterey (M1 Max). When restarting OBS, it takes about 30 seconds for the plugin to reconnect with OBS, but I'm guessing this is more of an issue with OBS or the Stream Deck than the plugin itself.

**Comment by lopcode** [comment]
> @CarrotCodes thank you for your work. I can confirm that the plugin works with OBS 28 RC2 for me on macOS Monterey (M1 Max). When restarting OBS, it takes about 30 seconds for the plugin to reconnect with OBS, but I'm guessing this is more of an issue with OBS or the Stream Deck than the plugin itself.

You're welcome 😊

I also noticed the slow connection behaviour, but only when closing and reopening OBS quickly - the first time seems fine for me. I suspect the socket isn't being closed properly on plug-in tear down.
