### ISSUE TITLE
Support PRISM Live studio

### ISSUE THREAD

**Issue by FabioZumbi12** [elgatosf/streamdeck-obs-plugin2#12]
I want to suggest suporting PRISM Live Studio https://prismlive.com/en_us/

This software is builded under OBS sources but StreamDeck only work after open OBS one time, and them, streamdeck detect Prism.

**Comment by Vide0phile** [comment]
Hi Fabio, there is a plugin available from PRISM Live available on Marketplace - [https://marketplace.elgato.com/product/prism-live-studio-66537253-7fa4-4ab6-924f-ee1cc0b8590a](https://marketplace.elgato.com/product/prism-live-studio-66537253-7fa4-4ab6-924f-ee1cc0b8590a)

If the plugin is not working as expected please reach out to PRISM Live at the support link on the Marketplace listing.
