### ISSUE TITLE
Building failed for Windows cmake-gui

### ISSUE THREAD

**Issue by PoWeR-Ding** [elgatosf/streamdeck-obs-plugin2#5]
Hello, I am getting an error when I use cmake-gui Building on Windows.
Prompt that libobs could not be found.

![微信截图_20220930201629](https://user-images.githubusercontent.com/112599924/193267969-c2c3a4cd-d97d-4889-a4cc-3a161e37ca9a.png)

CMake Warning at CMakeLists.txt:63 (message):
   Failed to detect version, using default instead.

 Version 5.3.2.0
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
CMake Error at OBSTemplate.cmake:64 (find_package):
  By not providing "Findlibobs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libobs", but
  CMake did not find one.

  Could not find a package configuration file provided by "libobs" with any
  of the following names:

    libobsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "libobs" to CMAKE_PREFIX_PATH or set
  "libobs_DIR" to a directory containing one of the above files.  If "libobs"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:146 (include)

Configuring incomplete, errors occurred!
See also "C:/Users/72709/Desktop/项目文件/Medcast Station项目/OBS开发/streamdeck-obs-plugin2/kaifa/CMakeFiles/CMakeOutput.log".

**Comment by PoWeR-Ding** [comment]
@elgatosf

**Comment by zvarnes** [comment]
Also having this issue

**Comment by Elgato-AStory** [comment]
Please use the OBS plugin build scripts now, obs-scripts/scripts/build-*

Those will automatically fetch the dependencies for an OBS 28 build
