### ISSUE TITLE
After renaming obs64.exe

### ISSUE THREAD

**Issue by PoWeR-Ding** [elgatosf/streamdeck-obs-plugin2#6]
@elgaosf 

After the obs64.exe is renamed, the program cannot detect obs.

![微信截图_20221001021006](https://user-images.githubusercontent.com/112599924/193331165-7f4f48a7-ba4a-41a9-a2ca-b6ed97e6e384.png)
![微信截图_20221001020755](https://user-images.githubusercontent.com/112599924/193331178-6272e0c4-8fa2-40c4-8c81-dda748d85882.png)

**Comment by Elgato-AStory** [comment]
This is not a use case that we are going to support.
