### ISSUE TITLE
Make OBS mixer volume adjustable trough StreamDeck+ rotary knobs

### ISSUE THREAD

**Issue by jeroenniesen** [elgatosf/streamdeck-obs-plugin2#8]
As a OBS and StreamDeck+ user, I want the rotary knobs on the StreamDeck+ to control the volume of an OBS mixer channel so I can adjust the volume easy while streaming/recording.

## Current situation
OBS does not work with rotary knobs of the StreamDeck+

## Desired situation
At least the OBS mixer can work with rotary knobs on the StreamDeck+

**Comment by Elgato-AStory** [comment]
Done as of the latest release.
